import type { Metadata } from "next";
import { Space_Grotesk } from "next/font/google";
import Nav from "@/components/nav";
import "./globals.css";

const fontMain = Space_Grotesk({
  variable: "--font-main",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={`${fontMain.className} font-sans antialiased`}>
        <Nav />
        <main>{children}</main>
      </body>
    </html>
  );
}
