import type { Metadata } from "next";
import { Poppins, Space_Grotesk, Inter } from "next/font/google";
import Nav from "@/components/nav";
import "./globals.css";

const fontGrotesk = Space_Grotesk({
  variable: "--font-grotesk",
  subsets: ["latin"],
  weight: "400",
});

const fontInter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: "400",
});

const fontPoppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${fontGrotesk.variable} ${fontPoppins.variable} ${fontInter.variable} font-grotesk antialiased`}
      >
        <Nav />
        <main>{children}</main>
      </body>
    </html>
  );
}
